/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.demian.rxjava;

import io.reactivex.Observable;

public class HelloRxJava {
    public void emit() {
        Observable
                .just("Hello", "Rxjava2!!")
                .subscribe(System.out::println);
    }

    public static void main(String[] args) {
        new HelloRxJava().emit();
    }
}
